### ISSUE TITLE
High CPU usage videosubscriptionsd and lsd

### ISSUE THREAD

**Issue by ghost** [callahanrts/bar#3]
I really love the bar widget, especially in combination with the kwm window manager, but the two process /usr/libexec/videosubscriptionsd and /usr/libexec/lsd are causing high CPU usage (about 50% on all four cores) while having the bar widget active. After closing Übersicht.app the CPU usage goes down. My MacBook Pro 2016 is running the latest version of macOS.

Is this a known bug? Or have is misconfigured something?

**Comment by callahanrts** [comment]
Thanks for the feedback! 

So far I haven't seen this before. It looks like both of those processes are coming from a launch daemon--which I don't think the default configuration for bar is using.  Do you have any other  Übersicht widgets installed? Can you also post what you have in your configuration (https://github.com/callahanrts/bar/blob/master/index.coffee#L1-L38)? I have seen high cpu usage in the past with the playing widget.
